# Generated by Django 3.2.5 on 2021-12-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200)),
                ('model_name', models.CharField(max_length=200, unique=True)),
                ('color', models.CharField(max_length=200)),
                ('jan_code', models.IntegerField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, default='smartphone-icon-logo.png', null=True, upload_to='')),
            ],
            options={
                'ordering': ['brand_name'],
            },
        ),
    ]
