# Generated by Django 3.2.5 on 2021-12-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiles',
            name='jan_code',
            field=models.IntegerField(unique=True),
        ),
    ]
