# Generated by Django 3.2.5 on 2021-12-27 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0002_alter_mobiles_jan_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mobiles',
            new_name='Mobile',
        ),
    ]
