# Generated by Django 3.2.5 on 2021-12-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0003_rename_mobiles_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='model_name',
            field=models.CharField(max_length=200),
        ),
    ]
